services:
  - type: web
    name: fire-dispatch-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn dispatch_center.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: dispatch_center.settings
      - key: PYTHON_VERSION
        value: 3.10
